services:
  example:
    build: 
      context: ./
      dockerfile: ./services/example/Dockerfile
    healthcheck:
      test: ["CMD-SHELL", "cat out.log | grep -c Init!"]
      interval: 5s
      timeout: 2s
      retries: 5


  catalog:
    build: 
      context: ./
      dockerfile: ./services/catalog/Dockerfile
    ports:
      - "8080:8080"
    hostname: "catalog"
    healthcheck:
      test: ["CMD-SHELL", "curl -f -Li localhost:8080/catalog | grep -c '200 OK'"]
      interval: 15s
      timeout: 2s
      retries: 5


  calculator:
    build: 
      context: ./
      dockerfile: ./services/calculator/Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      catalog:
          condition: service_started
    healthcheck:
      test: ["CMD-SHELL", "curl -f -Li catalog:8080/catalog/services/calculator | grep online | grep -c true"]
      interval: 15s
      timeout: 2s
      retries: 5


  openweatheradaptor:
    build: 
      context: ./
      dockerfile: ./services/openweatheradaptor/Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      catalog:
          condition: service_started
    healthcheck:
      test: ["CMD-SHELL", "curl -f -Li catalog:8080/catalog/services/openweatheradaptor | grep online | grep -c true"]
      interval: 15s
      timeout: 2s
      retries: 5
    environment:
      - OPENWETHERMAPAPIKEY=${OPENWETHERMAPAPIKEY}

  thingspeakadaptor:
    build: 
      context: ./
      dockerfile: ./services/thingspeakadaptor/Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      catalog:
          condition: service_started
    healthcheck:
      test: ["CMD-SHELL", "curl -f -Li catalog:8080/catalog/services/thingspeakadaptor | grep online | grep -c true"]
      interval: 15s
      timeout: 2s
      retries: 5
    environment:
      - THINGSPEAKAPIKEYTEMPERATUREWRITE=${THINGSPEAKAPIKEYTEMPERATUREWRITE}
      - THINGSPEAKAPIKEYTEMPERATUREREAD=${THINGSPEAKAPIKEYTEMPERATUREREAD}