services:
  example:
    build: 
      context: ./
      dockerfile: ./services/example/Dockerfile
    healthcheck:
      test: ["CMD-SHELL", "cat out.log | grep -c Init!"]
      interval: 5s
      timeout: 2s
      retries: 5

  catalog:
    build: 
      context: ./
      dockerfile: ./services/catalog/Dockerfile
    ports:
      - "8080:8080"
    hostname: "catalog"
    healthcheck:
      test: ["CMD-SHELL", "curl -f -Li localhost:8080/catalog | grep -c '200 OK'"]
      interval: 15s
      timeout: 2s
      retries: 5

  calculator:
    build: 
      context: ./
      dockerfile: ./services/calculator/Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      catalog:
          condition: service_started
    healthcheck:
      test: ["CMD-SHELL", "curl -f -Li catalog:8080/catalog/services/calculator | grep online | grep -c true"]
      interval: 15s
      timeout: 2s
      retries: 5

  arduinodevconn:
    build: 
      context: ./
      dockerfile: ./services/arduinodevconn/Dockerfile
    ports:
      - "8086:8086"
    depends_on:
      catalog:
          condition: service_started
    healthcheck:
      test: ["CMD-SHELL", "curl -f -Li catalog:8080/catalog/services/arduinodevconn | grep online | grep -c true"]
      interval: 15s
      timeout: 2s
      retries: 5
    # devices:
    #   - "/dev/i2c-1:/dev/i2c-1"  
    environment:
      - ONRASPBERRY=${ONRASPBERRY}

  raspberrydevconn:
    build: 
      context: ./
      dockerfile: ./services/raspberrydevconn/Dockerfile
    ports:
      - "8087:8087"
    depends_on:
      catalog:
          condition: service_started
    healthcheck:
      test: ["CMD-SHELL", "curl -f -Li catalog:8080/catalog/services/raspberrydevconn | grep online | grep -c true"]
      interval: 15s
      timeout: 2s
      retries: 5
    # devices:
    #   - "/dev/i2c-1:/dev/i2c-1"  
    environment:
      - ONRASPBERRY=${ONRASPBERRY}

  openweatheradaptor:
    build: 
      context: ./
      dockerfile: ./services/openweatheradaptor/Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      catalog:
          condition: service_started
    healthcheck:
      test: ["CMD-SHELL", "curl -f -Li catalog:8080/catalog/services/openweatheradaptor | grep online | grep -c true"]
      interval: 15s
      timeout: 2s
      retries: 5
    environment:
      - OPENWETHERMAPAPIKEY=${OPENWETHERMAPAPIKEY}

  thingspeakadaptor:
    build: 
      context: ./
      dockerfile: ./services/thingspeakadaptor/Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      catalog:
        condition: service_started
      arduinodevconn:
        condition: service_started
    healthcheck:
      test: ["CMD-SHELL", "curl -f -Li catalog:8080/catalog/services/thingspeakadaptor | grep online | grep -c true"]
      interval: 15s
      timeout: 2s
      retries: 5
    environment:
      - THINGSPEAKAPIKEYTEMPERATUREWRITE=${THINGSPEAKAPIKEYTEMPERATUREWRITE}
      - THINGSPEAKAPIKEYTEMPERATUREREAD=${THINGSPEAKAPIKEYTEMPERATUREREAD}
      - THINGSPEAKAPIKEYHUMIDITYWRITE=${THINGSPEAKAPIKEYHUMIDITYWRITE}
      - THINGSPEAKAPIKEYHUMIDITYREAD=${THINGSPEAKAPIKEYHUMIDITYREAD}
      - CHANNELIDTEMPERATURE=${CHANNELIDTEMPERATURE}
      - CHANNELIDHUMIDITY=${CHANNELIDHUMIDITY}

  deviceconfig:
    build: 
      context: ./
      dockerfile: ./services/deviceconfig/Dockerfile
    ports:
      - "8087:8087"
    depends_on:
      catalog:
          condition: service_started
    healthcheck:
      test: ["CMD-SHELL", "curl -f -Li catalog:8080/catalog/services/deviceconfig | grep online | grep -c true"]
      interval: 15s
      timeout: 2s
      retries: 5
    volumes:
      - ${PWD}/services/deviceconfig/confs.json:/app/services/deviceconfig/confs.json:rw