name: Docker Compose Actions Workflow
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate requirements.txt
        working-directory: src
        run: make genreq
      - name: Build the services
        working-directory: src
        run: docker-compose up -d
      #- name: Sleep for 20 seconds
      #  run: sleep 20s
      #  shell: bash
      - name: Check services healthiness
        uses: thegabriele97/dockercompose-health-action@main
        with:
          timeout: '60'
          workdir: 'src'
      - name: docker-compose ps
        working-directory: src
        run: |
          docker-compose ps
      - name: docker-compose logs
        working-directory: src
        run: |
          docker-compose logs
